#!/bin/bash

echo "Please manually restart the server by:"
echo "1. Stop the current 'go run ./cmd/api' process (Ctrl+C in the terminal)"
echo "2. Run 'go run ./cmd/api' again"
echo ""
echo "After restarting, run this test script again: ./test_user_flow.sh"
echo ""
echo "OR run these commands manually:"
echo ""
echo ""
echo "curl -X POST http://localhost:8080/users/ -H \"Content-Type: application/json\" -d '{\"username\": \"soumo2\", \"email\": \"soumosaha@example.com\", \"password\": \"helloworld@123\"}'"
echo ""
echo ""
echo "curl -X POST http://localhost:8080/users/login -H \"Content-Type: application/json\" -d '{\"email\": \"soumosaha@example.com\", \"password\": \"helloworld@123\"}'"
